user: "数据库用户名"     # 替换为你的数据库用户名
password: "数据库密码"   # 替换为你的数据库密码
host: "数据库地址"       # 如 localhost 或 IP
port: 3306              # 数据库端口号
database: "数据库名"     # 替换为你的数据库名称
charset: "utf8mb4"       # 字符集编码